apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpers.fullName" . }}-secret
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
type: Opaque
data:
  CLOUDFLARE_API_TOKEN: {{ .Values.cloudflare.apiToken | b64enc }}
  CLOUDFLARE_DNS_ZONE_NAME: {{ .Values.cloudflare.dnsZoneName | b64enc }}
  CLOUDFLARE_DNS_RECORD_NAMES: {{ .Values.cloudflare.dnsRecordNames | b64enc }}
